services:
  authorization_module:
    build:
      context: ./authorization_module
      dockerfile: Dockerfile
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db
    ports:
    - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - 8080:8000

volumes:
  db_data:
