services:
  authorization_module:
    build:
      context: ./authorization_module
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 9229:9229
    depends_on:
      - db
    volumes:
      - ./authorization_module/build:/usr/src/app/build
      - ./authorization_module/src:/usr/src/app/src
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db
    ports:
    - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
    - 8080:8080

volumes:
  db_data:
